<?php

/**
 * BaseXPaper
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $avatarpath
 * @property Doctrine_Collection $XArticles
 * 
 * @method string              getName()       Returns the current record's "name" value
 * @method string              getAvatarpath() Returns the current record's "avatarpath" value
 * @method Doctrine_Collection getXArticles()  Returns the current record's "XArticles" collection
 * @method XPaper              setName()       Sets the current record's "name" value
 * @method XPaper              setAvatarpath() Sets the current record's "avatarpath" value
 * @method XPaper              setXArticles()  Sets the current record's "XArticles" collection
 * 
 * @package    news
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseXPaper extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('x_paper');
        $this->hasColumn('name', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('avatarpath', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('XArticle as XArticles', array(
             'local' => 'id',
             'foreign' => 'paper_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}