<?php

/**
 * BaseXArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $paper_id
 * @property string $title
 * @property string $url
 * @property string $sumarry
 * @property XPaper $XPaper
 * 
 * @method integer  getPaperId()  Returns the current record's "paper_id" value
 * @method string   getTitle()    Returns the current record's "title" value
 * @method string   getUrl()      Returns the current record's "url" value
 * @method string   getSumarry()  Returns the current record's "sumarry" value
 * @method XPaper   getXPaper()   Returns the current record's "XPaper" value
 * @method XArticle setPaperId()  Sets the current record's "paper_id" value
 * @method XArticle setTitle()    Sets the current record's "title" value
 * @method XArticle setUrl()      Sets the current record's "url" value
 * @method XArticle setSumarry()  Sets the current record's "sumarry" value
 * @method XArticle setXPaper()   Sets the current record's "XPaper" value
 * 
 * @package    news
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseXArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('x_article');
        $this->hasColumn('paper_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('title', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('sumarry', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('XPaper', array(
             'local' => 'paper_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}