<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/03/07 01:01:30

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=x',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
