<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2012/03/07 01:01:30
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinecli' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrineconnectionprofiler' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfdoctrineconnectionlistener' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineroute' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'swift_doctrinespool' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrineformfiltergenerator' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrinecolumn' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrinegenerator' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfdoctrineformgenerator' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfvalidatordoctrinechoice' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sftesterdoctrine' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfdoctrinerecordi18nfilter' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrinerecord' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfwebdebugpaneldoctrine' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegenerateadmintask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinebuildfilterstask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinebasetask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinedropdbtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinedqltask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinebuildmodeltask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuildschematask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinedatadumptask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinemigratetask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrinebuildformstask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildsqltask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrineinsertsqltask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinebuilddbtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinecreatemodeltables' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedataloadtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrineexception' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfwidgetformdoctrinechoice' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',
  'sfformfilterdoctrine' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfformdoctrine' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfdoctrinepager' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',

  // project
  'baseformfilterdoctrine' => '/home/john/web/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'xpaperformfilter' => '/home/john/web/lib/filter/doctrine/XPaperFormFilter.class.php',
  'basexarticleformfilter' => '/home/john/web/lib/filter/doctrine/base/BaseXArticleFormFilter.class.php',
  'basexpaperformfilter' => '/home/john/web/lib/filter/doctrine/base/BaseXPaperFormFilter.class.php',
  'xarticleformfilter' => '/home/john/web/lib/filter/doctrine/XArticleFormFilter.class.php',
  'baseformdoctrine' => '/home/john/web/lib/form/doctrine/BaseFormDoctrine.class.php',
  'xpaperform' => '/home/john/web/lib/form/doctrine/XPaperForm.class.php',
  'basexpaperform' => '/home/john/web/lib/form/doctrine/base/BaseXPaperForm.class.php',
  'basexarticleform' => '/home/john/web/lib/form/doctrine/base/BaseXArticleForm.class.php',
  'xarticleform' => '/home/john/web/lib/form/doctrine/XArticleForm.class.php',
  'baseform' => '/home/john/web/lib/form/BaseForm.class.php',

  // project_model
  'xarticletable' => '/home/john/web/lib/model/doctrine/XArticleTable.class.php',
  'xpaper' => '/home/john/web/lib/model/doctrine/XPaper.class.php',
  'basexpaper' => '/home/john/web/lib/model/doctrine/base/BaseXPaper.class.php',
  'basexarticle' => '/home/john/web/lib/model/doctrine/base/BaseXArticle.class.php',
  'xpapertable' => '/home/john/web/lib/model/doctrine/XPaperTable.class.php',
  'xarticle' => '/home/john/web/lib/model/doctrine/XArticle.class.php',

  // application
  'myuser' => '/home/john/web/apps/frontend/lib/myUser.class.php',

  // modules
);
