<?php

/**
 * XArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class XArticleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object XArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('XArticle');
    }
}