<?php

/**
 * XPaperTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class XPaperTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object XPaperTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('XPaper');
    }
}